#!/bin/bash
set -e

# ============================================================
# Agent Fleet — One-Command Setup
# ============================================================
# Usage: ./setup.sh
#
# This script sets up the entire Agent Fleet stack:
#   1. Checks prerequisites (Docker, Node, Python)
#   2. Generates secure secrets
#   3. Builds and starts all containers
#   4. Runs database migrations
#   5. Creates a default user
#   6. Seeds default agents + workflows
#   7. Prints access URLs
# ============================================================

BOLD="\033[1m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
RED="\033[0;31m"
CYAN="\033[0;36m"
NC="\033[0m" # No Color

log() { echo -e "${GREEN}✓${NC} $1"; }
warn() { echo -e "${YELLOW}⚠${NC} $1"; }
err() { echo -e "${RED}✗${NC} $1"; exit 1; }
header() { echo -e "\n${BOLD}${CYAN}$1${NC}\n"; }

# ============================================================
# Step 1: Check prerequisites
# ============================================================
header "Step 1/7: Checking prerequisites"

command -v docker >/dev/null 2>&1 || err "Docker is not installed. Install from https://docker.com"
command -v docker compose >/dev/null 2>&1 || err "Docker Compose is not available. Update Docker Desktop."
log "Docker found: $(docker --version | head -1)"

command -v python3 >/dev/null 2>&1 || warn "Python3 not found (needed for seed script only)"
command -v node >/dev/null 2>&1 || warn "Node not found (needed for local dev only)"

# ============================================================
# Step 2: Generate secrets
# ============================================================
header "Step 2/7: Generating secrets"

if [ -f .env ]; then
    warn ".env already exists — skipping secret generation"
    warn "To regenerate, delete .env and re-run this script"
else
    POSTGRES_PASSWORD=$(openssl rand -hex 16)
    JWT_SECRET=$(openssl rand -hex 32)

    # Generate JWT keys using the secret
    # Anon key (role: anon)
    ANON_HEADER=$(echo -n '{"alg":"HS256","typ":"JWT"}' | base64 | tr -d '=' | tr '+/' '-_')
    ANON_PAYLOAD=$(echo -n '{"role":"anon","iss":"supabase","iat":1700000000,"exp":1900000000}' | base64 | tr -d '=' | tr '+/' '-_')
    ANON_SIGNATURE=$(echo -n "${ANON_HEADER}.${ANON_PAYLOAD}" | openssl dgst -sha256 -hmac "$JWT_SECRET" -binary | base64 | tr -d '=' | tr '+/' '-_')
    ANON_KEY="${ANON_HEADER}.${ANON_PAYLOAD}.${ANON_SIGNATURE}"

    # Service role key (role: service_role)
    SVC_PAYLOAD=$(echo -n '{"role":"service_role","iss":"supabase","iat":1700000000,"exp":1900000000}' | base64 | tr -d '=' | tr '+/' '-_')
    SVC_SIGNATURE=$(echo -n "${ANON_HEADER}.${SVC_PAYLOAD}" | openssl dgst -sha256 -hmac "$JWT_SECRET" -binary | base64 | tr -d '=' | tr '+/' '-_')
    SERVICE_ROLE_KEY="${ANON_HEADER}.${SVC_PAYLOAD}.${SVC_SIGNATURE}"

    cat > .env << ENVEOF
# Agent Fleet — Generated by setup.sh
# $(date)

# Supabase (local Docker)
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

# Supabase client config (for backend + frontend)
SUPABASE_URL=http://localhost:3000
SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

# LLM API Keys (add yours)
ANTHROPIC_API_KEY=
OPENAI_API_KEY=
GOOGLE_API_KEY=

# Local models (optional)
OLLAMA_API_BASE=http://host.docker.internal:11434
ENVEOF

    log "Secrets generated and saved to .env"
fi

# Create frontend .env
cat > fleet-ui/.env << FEEOF
VITE_SUPABASE_URL=http://localhost:3000
VITE_SUPABASE_ANON_KEY=$(grep ANON_KEY .env | head -1 | cut -d= -f2-)
VITE_API_BASE=http://localhost:8000
FEEOF
log "Frontend .env created"

# ============================================================
# Step 3: Build containers
# ============================================================
header "Step 3/7: Building containers"

docker compose build --quiet
log "All containers built"

# ============================================================
# Step 4: Start services
# ============================================================
header "Step 4/7: Starting services"

docker compose up -d
log "Services starting..."

# Wait for database to be healthy
echo -n "  Waiting for database"
for i in $(seq 1 30); do
    if docker compose exec -T supabase-db pg_isready -U postgres >/dev/null 2>&1; then
        echo ""
        log "Database is ready"
        break
    fi
    echo -n "."
    sleep 2
done

# Wait for auth service
echo -n "  Waiting for auth service"
for i in $(seq 1 20); do
    if curl -s http://localhost:9999/health >/dev/null 2>&1; then
        echo ""
        log "Auth service is ready"
        break
    fi
    echo -n "."
    sleep 2
done

# Wait for REST API
echo -n "  Waiting for REST API"
for i in $(seq 1 20); do
    if curl -s http://localhost:3000/ >/dev/null 2>&1; then
        echo ""
        log "REST API is ready"
        break
    fi
    echo -n "."
    sleep 2
done

# ============================================================
# Step 5: Run migrations
# ============================================================
header "Step 5/7: Running database migrations"

for migration in supabase/migrations/*.sql; do
    name=$(basename "$migration")
    echo "  Applying $name..."
    docker compose exec -T supabase-db psql -U postgres -d postgres -f "/docker-entrypoint-initdb.d/$name" 2>&1 | grep -E "^(CREATE|ALTER|INSERT|ERROR)" || true
done
log "Migrations applied"

# ============================================================
# Step 6: Create default user
# ============================================================
header "Step 6/7: Creating default user"

DEFAULT_EMAIL="admin@agentfleet.local"
DEFAULT_PASSWORD="agentfleet123"

# Create user via GoTrue API
SIGNUP_RESULT=$(curl -s -X POST http://localhost:9999/signup \
    -H "Content-Type: application/json" \
    -H "apikey: $(grep ANON_KEY .env | head -1 | cut -d= -f2-)" \
    -d "{\"email\":\"${DEFAULT_EMAIL}\",\"password\":\"${DEFAULT_PASSWORD}\"}" 2>&1)

USER_ID=$(echo "$SIGNUP_RESULT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id',''))" 2>/dev/null || echo "")

if [ -n "$USER_ID" ] && [ "$USER_ID" != "" ]; then
    log "Default user created: ${DEFAULT_EMAIL}"
    log "User ID: ${USER_ID}"
else
    warn "User creation may have failed or user already exists"
    warn "Response: $(echo "$SIGNUP_RESULT" | head -c 200)"
fi

# ============================================================
# Step 7: Seed default data
# ============================================================
header "Step 7/7: Seeding default agents + workflows"

if [ -n "$USER_ID" ] && [ "$USER_ID" != "" ] && command -v python3 >/dev/null 2>&1; then
    # Set env for seed script
    export SUPABASE_URL=http://localhost:3000
    export SUPABASE_SERVICE_ROLE_KEY=$(grep SERVICE_ROLE_KEY .env | head -1 | cut -d= -f2-)

    if [ -f ".venv/bin/activate" ]; then
        source .venv/bin/activate
    fi

    python3 scripts/seed_supabase.py "$USER_ID" 2>&1 || warn "Seed script failed — you can run it manually later"
else
    warn "Skipping seed — run manually: python scripts/seed_supabase.py <user_id>"
fi

# ============================================================
# Done!
# ============================================================
header "Setup Complete!"

echo -e "${BOLD}Access URLs:${NC}"
echo -e "  ${CYAN}Frontend UI:${NC}      http://localhost:3001"
echo -e "  ${CYAN}Backend API:${NC}      http://localhost:8000"
echo -e "  ${CYAN}Supabase Studio:${NC}  http://localhost:8080"
echo -e "  ${CYAN}Supabase REST:${NC}    http://localhost:3000"
echo ""
echo -e "${BOLD}Default credentials:${NC}"
echo -e "  Email:    ${GREEN}${DEFAULT_EMAIL}${NC}"
echo -e "  Password: ${GREEN}${DEFAULT_PASSWORD}${NC}"
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo -e "  1. Add your LLM API key to .env (ANTHROPIC_API_KEY or OPENAI_API_KEY)"
echo -e "  2. Open http://localhost:3001 and log in"
echo -e "  3. Try: fleet init --repo /path/to/your/project"
echo ""
echo -e "${BOLD}Commands:${NC}"
echo -e "  docker compose ps       — check service status"
echo -e "  docker compose logs -f  — view logs"
echo -e "  docker compose down     — stop all services"
echo -e "  docker compose up -d    — restart services"
echo ""
echo -e "${YELLOW}Remember to add your LLM API keys to .env!${NC}"
